### ISSUE TITLE
Feature: Simple minting with limits

### ISSUE THREAD

**Issue by fordN** [BlankFoundation/blank-nft#3]
Ensure users that are in the members list can easily mint a new NFT and apply a limit so they are only able to mint __ NFTS.

**Comment by jaredcosulich** [comment]
Made an attempt at this:

https://github.com/BlankFoundation/blank-nft/pull/6/files

Not sure if we want to include the ability to change the limit. Right now it's hard-coded to 5 in the pull request.

**Comment by jaredcosulich** [comment]
Would it be better to take the member info

mapping(address => bool) private _members;
mapping(address => uint8) private _memberMintCount;

And store it as a uint8 directly?

mapping(address => uint8) private _members;

Or as a struct?
