### ISSUE TITLE
Feature: Update tokenURI for all ids

### ISSUE THREAD

**Issue by fordN** [BlankFoundation/blank-nft#4]
Current implementation allows the foundation account to update tokenURIs per tokenID, but there will likely be instances where many or all tokens need their URI updated to a common set of metadata.

**Comment by jaredcosulich** [comment]
Debating how to approach this. As far as I know you can't iterate over a mapping. You could store all of the tokenIds as an array (I don't think that's being done anywhere in the contract yet), but that would add to storage costs. Maybe we just need to eat those storage costs?
